---
title: More About Me
toc: true
toc-title: Contents
toc-location: left
---

## **Education**

**Case Western Reserve University**

*2022-present*

Pursuing: BA in Biology, MPH, MD

**Episcopal High School**

*2019-2022*

Valedictorian

------------------------------------------------------------------------

## **Published Works**

**Factors Associated with Time to Definitive Surgery for Sebaceous Carcinoma**

Arya Patel, Omkar Pawar, Jeremy Bordeaux

Journal: JAAD

**Comparison of Acute and Late toxicities with Daily vs. Every-Other-Day Five Fraction Partial Breast Radiation Therapy**

Sean M Parker, Ahmed Halima, Sudha Amarnath, Maria Claudia Moncaliano, Arya Patel, Connor Spera, Elizabeth Obi, Cole Billena, Zahraa Al-Hilli, Sheen Cherian, Rahul Tendulkar, Chirag Shah

Journal: Journal: Pract Radiation Oncology

**Nutrition, Obesity and Seborrheic Dermatitis: A Systematic Review**

E. Woolhiser, N. Keime, Isaac Weber, Arya Patel, Madeline Adelman, R. Dellavalle

Journal: JMIR Dermatology

------------------------------------------------------------------------

## **Presentations and Posters**

**Geospatial Impacts of Melanoma Stage at Diagnosis: A Systematic Review (poster)**

Dakota Hitchcock ,Angela Loczi-Storm, Rebecca Bolen, Arya Patel, Robert Dellavalle MD PhD MSPH, Cory Dunnick MD

-   Accepted to AMA summit and “AMA Research Challenge” symposium

-   Colorado Medical Society Annual Meeting in Breckenridge, CO: 2nd place in research excellence

**Investigating TIGIT Blockade potential to enhance Car-T cell function on Solid Tumors**

CANSUR Symposium Oral Presentation

Patel, A; Franklin, J;Das I.; Wald D.

**Characterization and Annotation of novel Azotobacter bacteriophages**

SEA-PHAGES Symposium Poster Presentation

Patel, A; Sun, T; Cunliffe O.; John J; Ward R

**The Effect of Klebsiella Pneumoniae Endotoxins on Lung Derived Mesenchymal Stem Cell Bioenergetic Processes**

Louisiana Science Fair Poster Presentation 

Patel A., Rangaswamy R.

-   1st place in Biomedical Sciences

------------------------------------------------------------------------

## **Other Publications**

**“Attending School as a Child with Cancer”**

RedTreeHouse

*MAY 2023-present* 

-   “Pro Picks” centered around oncology topics to help guide parents whose children are cancer patients 

------------------------------------------------------------------------
