# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "ARYA PATEL"                                # Your name
  description: "Arya Patel is a student at Case Western Reserve University"  
  image: "docs/National_Merit-6916.jpg"
  
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    
    # your sub-pages
    left:
      - text: "Welcome"
        href: welcome/index.qmd
      - text: "More About Me"
        href: projects/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "My Blog"
        href: blog/index.qmd
    
    # your social media handles
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/arya-patel-480a60242/
      - icon: github
        href: https://www.github.com/axp1031
      - icon: instagram
        href:  https://instagram.com/arya_patel14
      - icon: envelope
        aria-label: email
        href: "mailto:axp1031@case.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
project:
  type: website
  output-dir: docs
  resources:
    - "cv.pdf"

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true